name: "Sample pipeline/workflow" # Name of the pipeline

on:
    push:
        branches:
            - master # Trigger the pipeline on push to master branch
            - main # Trigger the pipeline on push to main branch
    pull_request:
        branches:
            - main 
    workflow_dispatch: # Manual trigger from the UI

jobs:
    sampleJob:
        runs-on: ubuntu-latest # Run the pipeline on ubuntu-latest runner
        steps:
            - name: "Print hello world"
              run: echo "Hello world"

            - name: "Print current directory"
              run: pwd

            - name: "List files in the current directory"
              run: ls -l
            
            - name: "Python install"
              run: |
                python -m pip install --upgrade pip
                pip install Flask

            - name: "Check Python version"
              run: python --version

            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                python-version: '3.12' # Specify Python version, e.g., 3.8 or 3.9

            - name: "Clone the repository"
              uses: actions/checkout@v3

            - name: "Install dependencies from requirements.txt"
              run: |
                if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

            - name: "List files in the current directory"
              run: ls

