name: "Sample pipeline/workflow" # Name of the pipeline

on:
    push:
        branches:
            - master # Trigger the pipeline on push to master branch
            - main # Trigger the pipeline on push to main branch
    pull_request:
        branches:
            - main 
    workflow_dispatch: # Manual trigger from the UI

jobs:
    sampleJob:
        runs-on: ubuntu-latest # Run the pipeline on ubuntu-latest runner
        steps:
            - name: "Print hello world"
              run: echo "Hello world"

            - name: "Print current directory"
              run: pwd

            - name: "List files in the current directory"
              run: ls -l
            
            - name: "Python install"
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: "Run Flask app"
              env:
                FLASK_APP: app.py
                FLASK_ENV: development
              run: |
                python -m venv venv
                . venv/bin/activate
                flask run &
                sleep 10 # Allow server to start before running tests

            - name: "Test Flask app"
              run: |
                curl -f http://127.0.0.1:5000/
